# Generated by Django 3.0.3 on 2020-04-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caunt', models.IntegerField(verbose_name='Кількість продуктів')),
                ('slug', models.SlugField()),
                ('weist_dish', models.FloatField(verbose_name='Вага страви')),
                ('total_dish_kll', models.FloatField(verbose_name='Калорійність страви')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, unique=True, verbose_name="Ім'я користувача")),
                ('person_birthday', models.DateField(max_length=8, verbose_name='День народження')),
                ('person_gender', models.CharField(choices=[('male', 'Чол.'), ('female', 'Жін.')], max_length=150, verbose_name='Стать')),
                ('person_work_group', models.CharField(choices=[('the_first', 'перша'), ('the_second', 'друга'), ('the_third', 'третя')], max_length=150, verbose_name='Робоча група')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, unique=True, verbose_name='Назва продукту')),
                ('categori_product', models.CharField(choices=[('vegetable', 'овочі'), ('fruit', 'фрукти'), ('meat', "м'ясо"), ('seafood', 'морепродукти')], max_length=150, verbose_name='Категорія продукту')),
                ('protein', models.FloatField(verbose_name='Білки')),
                ('fat', models.FloatField(verbose_name='Жири')),
                ('carbohydrat', models.FloatField(verbose_name='Вугливоди')),
                ('kll', models.FloatField(verbose_name='Калорійність')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='Work_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField(max_length=8, verbose_name='Вік')),
                ('energy', models.FloatField(verbose_name='Енергія')),
                ('number_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Person', verbose_name='Робоча група')),
            ],
            options={
                'verbose_name': 'Робоча група',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kll', models.FloatField(verbose_name='Загальна калорійність меню')),
                ('dish', models.ManyToManyField(to='mainapp.Dish', verbose_name='Назва страви')),
            ],
            options={
                'verbose_name': 'Меню',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product', verbose_name='Назва продукту'),
        ),
    ]
